<template>
  <v-app-bar
    absolute
    :elevation="0"
    hide-on-scroll
    class="border-b"
  >
    <v-toolbar-title>
      <img
        src="/images/logo-koran-utama.png"
        alt=""
      >
    </v-toolbar-title>
  </v-app-bar>
</template>