<template>
  <v-app-bar
    absolute
    :elevation="0"
    hide-on-scroll
    class="border-b"
  >
    <v-btn
      icon
      class="hidden-xs-only"
      v-if="$route.name === 'DetailPost'"
      @click="$router.back()"
    >
      <v-icon>mdi-arrow-left</v-icon>
    </v-btn>
    <v-toolbar-title>
      <img
        src="/images/logo-koran-utama.png"
        alt=""
      >
    </v-toolbar-title>
  </v-app-bar>
</template>